modLoader = "javafml"
loaderVersion = "${forge_loader_version_range}"
license = "${license}"

[[mods]]
modId = "memory_display_mod"
version = "${version}"
displayName = "${mod_name}"
displayURL="https://github.com/tranquil209kid/memory-display"
logoFile = "icon.png"
credits = "${credits}"
authors = "${mod_author}"
description = '''${description}'''

[[dependencies.memory_display_mod]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.memory_display_mod]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"